COMP: Fix missing include directory for Python.h
The error appears when compiling the RTK wrapping independently of ITK
with the script utilities/build_rtk_python.sh:

  In file included from /home/srit/src/itk/lin64-PythonWrapping/Wrapping/castxml_inputs/itkPyBufferRTK.cxx:16:
  /home/srit/src/itk/itk/Modules/Bridge/NumPy/include/itkPyBuffer.h:30:10: fatal error: 'Python.h' file not found
     30 | #include <Python.h>
        |          ^~~~~~~~~~
  1 error generated.
  gmake[2]: *** [Wrapping/Modules/RTK/CMakeFiles/RTKCastXML.dir/build.make:329: /home/srit/src/itk/lin64-PythonWrapping/Wrapping/castxml_inputs/itkPyBufferRTK.xml] Error 1
  gmake[2]: Leaving directory '/home/srit/src/rtk/lin64-toto'
  gmake[1]: *** [CMakeFiles/Makefile2:2357: Wrapping/Modules/RTK/CMakeFiles/RTKCastXML.dir/all] Error 2
  gmake[1]: Leaving directory '/home/srit/src/rtk/lin64-toto'
  gmake: *** [Makefile:146: all] Error 2