BUG: Fix Python argument parser for Python 3.9
Fixes error message
```
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
This is because `str | None` syntax is only supported in Python 3.10 or
later (https://peps.python.org/pep-0604/).