COMP: Restore namespace itk in IO factory files
This is a modification of commit a40080a3b that removed the itk namespace in IO factories,
Fix compilation error like "undefined reference to `itk::DCMImagXImageIOFactoryRegister__Private()"